- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/RobotMap.java
- InfiniteRecharge/src/main/java/frc/robot/operatorinterface/OI.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/BitBucketSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/Subsystems.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/copypaste/CopyPasteSubsystem.txt
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/AutoDrive.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/Idle.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/RotationDrive.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/VelocityDrive.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/navigation/NavigationSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/utils/CommandUtils.java
- InfiniteRecharge/src/main/java/frc/robot/utils/JoystickScale.java
- InfiniteRecharge/src/main/java/frc/robot/utils/RisingEdgeFilter.java
- InfiniteRecharge/src/main/java/frc/robot/utils/math/MathUtils.java
- InfiniteRecharge/src/main/java/frc/robot/utils/talonutils/TalonUtils.java
- Robot class takes all subsystems and then creates an object with all of them, which it "injects" into each subsystem, each of which decide what to do with the data
- Created Subsystems enum to "ID" subsystems
- created Drive subsystem
- updated Navigation subsystem to work with it
- added the "CopyPasteSubsystem" - you copy paste it in and then put in any subsystem specific changes wherever there's an error
- and fixed indentation and style consistency issues in Robot  and BBSubsystem classes
> Managing Subsystem dependencies Try 1

- InfiniteRecharge/build.gradle
> Added automatic dependency refresh to build.gradle

- InfiniteRecharge/.vscode/launch.json
Added a windows path environment override to enable the simulator to work on windows.
Removed unnecessary  -Djava.library.path
> Added windows Path var to launch.json

- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/operatorinterface/OI.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/intake/IntakeSubsystem.java
add POV for the D-pad
create booleans for intaking and outaking in OI.java
create enum for the 3 states:
intaking, outaking, and off
> finish setup for intake subsystem

- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/config/MotorConfig.java
- InfiniteRecharge/src/main/java/frc/robot/config/urations/JuniorConfiguration.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/utils/talonutils/MotorUtils.java
-Added a velocity control mode to the feeder and shooter, fire using velocity control with L1 and R1.
-Changed the drive motor IDs back to arrays in the config.
-Added a shooterGearRatio to the config.
-Renamed config.shooter.gearRatio to config.shooter.azimuthGearRatio
-rotateToDeg now uses the gear ratio of the azimuth.
> Shooter & feeder velocity control, minor Config changes, rotateToDeg fix

- Auto Simulator/controlConstants.m
- Auto Simulator/ctrb_obsv_test.m
- Auto Simulator/getFPhysics.m
- Auto Simulator/getInpMatControl.m
- Auto Simulator/getInpMatPhysics.m
- Auto Simulator/getSysMatControl.m
- Auto Simulator/getSysMatPhysics.m
- Auto Simulator/physicsConstants.m
- Auto Simulator/simulate.m
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/navigation/NavigationConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/navigation/NavigationSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/utils/data/DoubleDataWindow.java
- output more IMU telemetry to dashboard (and rearrange structure so Navigation does this)
- report variances of IMU data
- added WIP MATLAB simulator to folder
> IMU telemetry, variances, and MATLAB

- InfiniteRecharge/FRCSim/config.yaml
> Updated config.yaml to support positional sim

- Auto Simulator/simulate.m
- InfiniteRecharge/src/main/java/frc/robot/operatorinterface/OI.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/navigation/RobotSystem.java
- InfiniteRecharge/src/main/java/frc/robot/utils/control/statespace/estimators/LuenbergerObserver.java
- InfiniteRecharge/src/main/java/frc/robot/utils/control/statespace/estimators/kalman/KalmanFilter.java
- InfiniteRecharge/src/main/java/frc/robot/utils/control/statespace/models/linearized/CLinearizedModel.java
- InfiniteRecharge/src/main/java/frc/robot/utils/control/statespace/models/linearized/LinearizedModel.java
- InfiniteRecharge/src/main/java/frc/robot/utils/control/statespace/models/linearized/Linearizer.java
- InfiniteRecharge/src/main/java/frc/robot/utils/control/statespace/models/ltif/LTIFModel.java
- InfiniteRecharge/src/main/java/frc/robot/utils/control/statespace/models/ltift/CLTIFtModel.java
- InfiniteRecharge/src/main/java/frc/robot/utils/control/statespace/models/ltift/LTIFtModel.java
- InfiniteRecharge/src/main/java/frc/robot/utils/control/statespace/models/motor/MotorPosition.java
- InfiniteRecharge/src/test/java/frc/robot/utils/control/statespace/models/ModelTester.java
- put turn and forward on different joysticks per request
- correct JUNIOR's track width to be accurate according to characterization
- characterization! still not 100% sure how to use these values. changes coming Soon(TM)
- Kalman filter implementation
> Drive changes and Kalman filter

- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
-Tuned velocity PIDFs for drive motors.
-Added additional smart dashboard debug information to the drive subsystem.
-Changed drive motors to TalonFXes.
> PIDFs, the smart dashboard, and the drive subsystem.

- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ball_management/BallManagementSubsystem.java
-Added the BallManagementSubsystem.
-Added config functionality to BallManagementSubsystem.
-Completely reworked controls.
-Fixed ShooterSubsystem (SensorPhase is already covered by config.)
-Completely reworked most of the ShooterSubsystem.
> BallManagementSubsystem, controls, etc.

- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/operatorinterface/OI.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
-Added new axis and buttons to the OI.
-Reworked controls to use new OI buttons and axis.
-Re-added the code that makes rotateToDeg, rotateByDeg, rotate, etc. work. (oops)
-Moved the BallManagementSubsystem.initialize from the ShooterSubsystem constructor to the ShooterSubsystem initialize.
> Reworked controls, shooter fix, and moved BallManagementSubsystem.initialize

- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/intake/IntakeSubsystem.java
correct small fix regarding the pivet of the pneumatics
> Pneumatics 

- InfiniteRecharge/src/main/java/frc/robot/operatorinterface/OI.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
deleted SparkMAX imports that we will never use
> Teeny itty bitty fix

- InfiniteRecharge/src/main/java/frc/robot/Main.java
- InfiniteRecharge/vendordeps/navx_frc.json
> Kauai Labs update

- InfiniteRecharge/FRCSim/config.yaml
- InfiniteRecharge/src/main/java/frc/robot/utils/talonutils/MotorUtils.java
Also moved motor config Kf/Kp constants below encoder setting to work with the lame simulator.
> Updated config.yaml with new motor ids

- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/config/MotorConfig.java
- InfiniteRecharge/src/main/java/frc/robot/config/urations/JuniorConfiguration.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/utils/talonutils/MotorUtils.java
-Added soft limit functionality to the azimuthMotor. (Temporarily disabled to avoid conflicts.)
-Slightly changed junior config.
-Slightly changed config.
-Added more debug info to the shooter.
> Soft limit functionality, config, and debug info.

- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
create array for all the subsystems so that the code is more organized and changed diagnosticsInitialize and diagnosticsPeriodic to test Init and testPeriodic respectively
> code cleanup

- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/vision/VisionSubsystem.java
I forgot this before, without this it wouldn't work
> Add calculation method to periodic

- Auto Simulator/badUpdate.m
- Auto Simulator/ctrb_obsv_test.m
- Auto Simulator/getABad.m
- Auto Simulator/getCPhysics.m
- Auto Simulator/getOutputPhysics.m
- Auto Simulator/physicsConstants.m
- Auto Simulator/simulate.m
- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/config/urations/JuniorConfiguration.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/AutoDrive.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/navigation/NavigationSubsystem.java
- InfiniteRecharge/vendordeps/Phoenix.json
- InfiniteRecharge/vendordeps/navx_frc.json
- changed system dynamics to be less correct but more accurate... will need to see why old dynamics were not working
- added random process and output noise
- graph more useful things
> More Kalman filters!

- InfiniteRecharge/src/main/java/frc/robot/RobotMap.java
- InfiniteRecharge/src/main/java/frc/robot/operatorinterface/OI.java
-OI buttons and axis are now static and no longer private.
> OI changes.

- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/config/urations/FocusedExcellenceConfiguration.java
- InfiniteRecharge/src/main/java/frc/robot/config/urations/JuniorConfiguration.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/AutoDrive.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveUtils.java
- Added radius and track width to config along with values for the robots we have
- implemented function that sets the wheel speeds of the drive base, used by the RAMSETE controller
- got rid of unused imports and methods
- also DriveConstants now needs to use the config to calculate constants based on config values
> Radius & track width config and setWheelSpeeds

- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
We the People of the Bit Buckets Software team, in Order to form a more perfect subteam, establish coding conventions, insure no deviation from these conventions, provide against Team 60's defence, promote the true pronunciation of "PID", and secure the Rights of the Software People to ourselves and our Posterity, do ordain and establish this Constitution for the Bit Buckets Robotics team
Article 1.
Section 1. Configuration files shalt hath public variables
Section 2. Subsystem constants shalt hath package private variables
Section 3. Utility constants shalt hath public final variables
Section 4. Subsystems and Other Classes shalt hath private final variables or private variables when applicable
Section 5. Any deviation will result in being put in a peach, or capital punishment.
> (Mostly) Modified shooter subsystem and config to fit new conventions.

- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/config/urations/JuniorConfiguration.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ball_management/BallManagementSubsystem.java
- BallManagementSubsystem.fire will now wait for the shooter to be spun up before doing anything.
- ShooterSubsystem.spinUp now waits for the ballPropulsionMotor to be spun up before spinning up the feeder.
- Added a feederSpinUpDeadband to the ShooterConfig.
> ShooterSubsystem and BallManagementSubsystem changes

- InfiniteRecharge/src/main/java/frc/robot/subsystem/navigation/NavigationSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
- odometry!
- other small fixes
> Today is a great day

- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Changed elevationGearRatio to 40 / 70

- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
-Set the elevation soft limits to 60 and 0.
-Target position soft limits now use degrees for -1 detection.
> Some soft limit changes

- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveUtils.java
- InfiniteRecharge/src/main/java/frc/robot/utils/math/Vector3d.java
Might change the way I'm calculating maximum acceleration
> RAMSETE config and maximum acceleration

- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
Specifically the code that stops the BMS from firing if the shooter isn't up to speed, and the code that makes sure the feeder only feeds the shooter when the shooter is up to speed.
> Temporarily commented out some code for Wednesday's testing

- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
-ShooterSubsystem.fire() is now ShooterSubsystem.spinBMS()
-spinBMS no longer requires the shooter to be spun up to do anything.
> BMS changes.

- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/BitBucketSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/climber/ClimbSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/copypaste/TestSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/navigation/NavigationSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/pidhelper/PIDHelperSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/intake/IntakeSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ball_management/BallManagementSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/spinnyboi/SpinnyBoiSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/vision/VisionSubsystem.java
-Added dashboardPeriodic to BitBucketSubsystem
-Renamed initializeBaseDashboard to dashboardInit
-Moved SmartDashboard.putNumber calls from initialize/testInit and periodic to dashboardInit and dashboardPeriodic (In shooter and intake subsystems only so far)
> Dashboard refactoring.

- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/intake/IntakeSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
- Fixed a bug with the IntakeSubsystem initializing incorrectly after dashboardInit changes
- Fixed shooter spinUp to properly turn off feeder when speed drops
- Reduced feeder error amount
- Set feeder to break when stopped
> Fixed IntakeSubsystem bug and shooter spinup bug

- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/config/urations/FocusedExcellenceConfiguration.java
- InfiniteRecharge/src/main/java/frc/robot/config/urations/JuniorConfiguration.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- combination of lack of sensor phase and inversion being enabled that shouldn't be
> Fixed motor inversion

- InfiniteRecharge/src/main/java/frc/robot/utils/control/statespace/estimators/kalman/UnscentedKalmanFilter.java
- InfiniteRecharge/src/main/java/frc/robot/utils/control/statespace/models/StateSpaceModel.java
- InfiniteRecharge/src/main/java/frc/robot/utils/control/statespace/models/linearized/LinearizedModel.java
- InfiniteRecharge/src/main/java/frc/robot/utils/math/MathUtils.java
> Cholesky decomposition and starting Unscented Kalman filter

- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
-Added a rolling average to the spinUp method's check to prevent the feeder from stuttering.
> Feeder rolling average

- InfiniteRecharge/FRCSim/config.yaml
- InfiniteRecharge/src/test/java/frc/robot/subsystem/drive/DriveSubsystemTest.java
Also added DriveSubsystemTest class
> Cleaned up config.yaml and added correct radius values

- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
The stupid fast forward system had an issue which took about twice the amount of time to deal with as the writing of the code itself.
> Added a motor(Current ID 16) which follows the shooter motor.

- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
-Changed from .48 / 1 to .45 / 1.
> Shooter gear ratio.

- InfiniteRecharge/src/main/java/frc/robot/subsystem/BitBucketSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterCalculator.java
- InfiniteRecharge/src/test/java/frc/robot/Sim.java
- InfiniteRecharge/src/test/java/frc/robot/subsystem/drive/DriveUtilsTest.java
- InfiniteRecharge/src/test/java/frc/robot/subsystem/scoring/shooter/ShooterCalculatorTest.java
- InfiniteRecharge/src/test/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystemTest.java
Also moved DriverStation.getInstance() into BitBucketsSubsystem constructor for unit tests.
> Fixed Sim distance calc, ShooterCalculatorTest, Added DriveUtils test

- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
> Added elevation limit switch functionality

- InfiniteRecharge/FRCSim/config.yaml
Also added some heft to the shooter so it would trigger the BMS
> Updated motor ids in sim.

- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
-Dashboard Elevation Target changed to 45 (from 10)
-DEFAULT_SHOOTER_VELOCITY_RPM changed to 5000.4183 (from 4183)
> Changed some defaults

- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
-spinUp is now called in shooter periodic if spinningUp is true.
-Instead of calling spinUp, the robot will call startSpinningUp.
-autoAim now turns on the limelight, and stopAutoAim is now called when you let go of the button, which turns them off.
> spinUp changes

- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
> Code that hurts my soul

- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
> Code that has been written by me.

- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterCalculator.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/vision/VisionConstants.java
resolves #198 and also resolves #16
> spins shooter to velocity based on distance when autoAim is pressed

- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/test/java/frc/robot/subsystem/drive/DriveSubsystemTest.java
> Fixed gearRatio issue with get[Left|Right]Velocity_mps

- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/operatorinterface/OI.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/climber/ClimbConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/climber/ClimbSubsystem.java
uses the axes now and other cool stuff
> Change how climb rewinding works

- InfiniteRecharge/FRCSim/config.yaml
- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/auto/FullTrajectory.java
> organize trajectories and make new trajectory for the opposition trench

- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
confusing and inconsistent, only use it when it'll work for different start positions too
> don't use fieldconstants

- InfiniteRecharge/FRCSim/config.yaml
- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/auto/FieldConstants.java
- InfiniteRecharge/src/test/java/frc/robot/subsystem/drive/AutoTrajectoryTest.java
- InfiniteRecharge/src/test/java/frc/robot/subsystem/drive/auto/FieldConstantsTest.java
> use fieldconstants! and set end velocity while making trajectories

- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
-All SmartDashboard calls (except ones within if statements) have been moved to dashboard periodic.
-All SmartDashboard.get____ statements have been moved to dashboard periodic and are now used to update variables every second.
-ALL SmartDashboard.put____ statements are only called if telemetry is enabled.
-Moved Dashboard periodic and disable to the bottom of the subsystem.
> Shooter dashboard reformatting

- InfiniteRecharge/FRCSim/config.yaml
- InfiniteRecharge/build.gradle
- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/auto/FieldConstants.java
- InfiniteRecharge/src/test/java/frc/robot/subsystem/drive/auto/FieldConstantsTest.java
note:
for center trajectory:
a) it doesnt shoot before it goes pickup balls so ig we need to hardcode stuff for that
b) it crashes into the wall
> work on the center-right auto trajectory

- InfiniteRecharge/FRCSim/config.yaml
- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/auto/FieldConstants.java
wait till shooter spins up, clean up some code and some other stuff
> fixes for our trench auto trajectory

- InfiniteRecharge/src/main/java/frc/robot/subsystem/vision/VisionSubsystem.java
> calculate ty from distance method

- InfiniteRecharge/build.gradle
- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/climber/ClimbConstants.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/climber/ClimbDashboard.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/climber/ClimbSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/utils/dashboard/DashboardFactory.java
- InfiniteRecharge/src/main/java/frc/robot/utils/dashboard/DashboardHandler.java
- InfiniteRecharge/src/main/java/frc/robot/utils/dashboard/annotations/Dashboard.java
- InfiniteRecharge/src/main/java/frc/robot/utils/dashboard/annotations/Default.java
- InfiniteRecharge/src/main/java/frc/robot/utils/dashboard/annotations/DefaultBoolean.java
- InfiniteRecharge/src/main/java/frc/robot/utils/dashboard/annotations/DefaultString.java
- InfiniteRecharge/src/main/java/frc/robot/utils/dashboard/annotations/Key.java
- InfiniteRecharge/src/test/java/frc/robot/Sim.java
- InfiniteRecharge/src/test/java/frc/robot/subsystem/SubsystemTest.java
- InfiniteRecharge/src/test/java/frc/robot/utils/dashboard/DashboardHandlerTest.java
Updated ClimbSubsystem with the new ClimbDashboard interface
> Added utility to create SmartDashboard proxy classes from interfaces

- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/config/Config.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/drive/DriveSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/navigation/NavigationSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/navigation/systems/RobotSystem1.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/navigation/systems/RobotSystemConfig.java
- InfiniteRecharge/src/main/java/frc/robot/utils/data/noise/Noise.java
next step is to make it calculate stuff but that's scary so we're stopping here :)
> Adding noise covariances to KF and initial pose

- InfiniteRecharge/build.gradle
- InfiniteRecharge/src/main/java/frc/robot/Robot.java
- InfiniteRecharge/src/main/java/frc/robot/config/ShooterConfig.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/BitBucketSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/navigation/NavigationSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterCalculator.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ShooterSubsystem.java
- InfiniteRecharge/src/main/java/frc/robot/subsystem/scoring/shooter/ball_management/BallManagementSubsystem.java
- InfiniteRecharge/src/test/java/frc/robot/subsystem/scoring/shooter/ShooterCalculatorTest.java
-BitBucketSubsystem now implements Loggable.
-A few variables now use Oblog.
-Logged the AHRS to the smart dashboard (under the name "NavX")
-Fixed an issue with the ShooterCalculator and config.
-You can now move the feeder using the SmartDashboard.
-Added Oblog as a dependency.
> Initial Oblog Check in
